import { FullMetricsPayload, HealthAlert } from './types';

export const INITIAL_MOCK_METRICS: FullMetricsPayload = {
  instance: {
    version: 'Microsoft SQL Server 2022 (RTM-CU14) (KB5038325) - 16.0.4135.4 (X64)',
    edition: 'Enterprise Edition: Core-based Licensing (64-bit)',
    level: 'CU14',
    instanceName: 'MSSQLSERVER',
    machineName: 'PROD-SQL-NODE01',
    collation: 'SQL_Latin1_General_CP1_CI_AS',
    totalMemoryGB: 128,
    logicalCpus: 32,
    uptimeHours: 412.5,
    isClustered: true,
    isAlwaysOn: true,
  },
  cpu: {
    totalUsagePct: 68.4,
    sqlProcessUsagePct: 54.2,
    otherProcessesUsagePct: 14.2,
    systemIdlePct: 31.6,
    workerThreadsCount: 284,
    runnableTasksCount: 4,
    pendingIoCount: 12,
    schedulerYields: 1845920,
    history: [
      { timestamp: '14:20', sqlPct: 42, totalPct: 50 },
      { timestamp: '14:21', sqlPct: 45, totalPct: 53 },
      { timestamp: '14:22', sqlPct: 62, totalPct: 71 },
      { timestamp: '14:23', sqlPct: 78, totalPct: 89 },
      { timestamp: '14:24', sqlPct: 84, totalPct: 94 },
      { timestamp: '14:25', sqlPct: 72, totalPct: 83 },
      { timestamp: '14:26', sqlPct: 58, totalPct: 69 },
      { timestamp: '14:27', sqlPct: 51, totalPct: 62 },
      { timestamp: '14:28', sqlPct: 65, totalPct: 76 },
      { timestamp: '14:29', sqlPct: 54, totalPct: 68 },
    ],
  },
  memory: {
    totalPhysicalMemoryMB: 131072,
    availablePhysicalMemoryMB: 18420,
    sqlTargetMemoryMB: 114688,
    sqlTotalMemoryMB: 112500,
    bufferCacheHitRatioPct: 99.4,
    pageLifeExpectancySec: 1450,
    memoryGrantsPending: 0,
    freeMemoryMB: 2188,
    grantedWorkspaceMemoryMB: 8450,
    clerks: [
      { name: 'MEMORYCLERK_SQLBUFFERPOOL', type: 'Buffer Pool', sizeMB: 84200, pctOfTotal: 74.8, description: 'Caches data and index pages read from disk' },
      { name: 'MEMORYCLERK_SQLQERESERVATIONS', type: 'Query Execution', sizeMB: 8450, pctOfTotal: 7.5, description: 'Memory grants reserved for active hash joins & sorts' },
      { name: 'CACHESTORE_SQLCP', type: 'SQL Plans (Ad-Hoc)', sizeMB: 6800, pctOfTotal: 6.0, description: 'Compiled dynamic SQL and ad-hoc query plans' },
      { name: 'CACHESTORE_OBJCP', type: 'Object Plans', sizeMB: 4950, pctOfTotal: 4.4, description: 'Stored procedures, triggers, and UDF execution plans' },
      { name: 'MEMORYCLERK_SQLSTORENG', type: 'Storage Engine', sizeMB: 3800, pctOfTotal: 3.4, description: 'Lock manager, transaction manager, and metadata' },
      { name: 'MEMORYCLERK_SQLGENERAL', type: 'General Internal', sizeMB: 2400, pctOfTotal: 2.1, description: 'Internal server tasks and connection buffers' },
      { name: 'MEMORYCLERK_HOST', type: 'CLR & Extended', sizeMB: 1900, pctOfTotal: 1.7, description: 'External assemblies, XEvents, and host services' },
    ],
  },
  disk: {
    drives: [
      { drive: 'C:\\', totalGB: 500, freeGB: 210, usedGB: 290, usedPct: 58.0, label: 'OS & System', isSystemDrive: true },
      { drive: 'D:\\Data_LUN01', totalGB: 4096, freeGB: 680, usedGB: 3416, usedPct: 83.4, label: 'SQL MDF Primary Data', isSystemDrive: false },
      { drive: 'E:\\Data_LUN02', totalGB: 4096, freeGB: 1120, usedGB: 2976, usedPct: 72.7, label: 'SQL NDF Secondary Data', isSystemDrive: false },
      { drive: 'L:\\Log_LUN01', totalGB: 2048, freeGB: 295, usedGB: 1753, usedPct: 85.6, label: 'Transaction Logs (LDF)', isSystemDrive: false },
      { drive: 'T:\\TempDB_NVMe', totalGB: 1024, freeGB: 640, usedGB: 384, usedPct: 37.5, label: 'Ultra-Fast TempDB Array', isSystemDrive: false },
      { drive: 'B:\\Backups_NFS', totalGB: 8192, freeGB: 3420, usedGB: 4772, usedPct: 58.3, label: 'Enterprise Backup Vault', isSystemDrive: false },
    ],
    dataFilesTotalGB: 6392,
    logFilesTotalGB: 1753,
    tempdb: {
      totalMB: 393216,
      userObjectsMB: 98400,
      internalObjectsMB: 45200,
      versionStoreMB: 31200,
      freeSpaceMB: 218416,
    },
    ioStalls: [
      { dbName: 'ERP_Production', fileName: 'ERP_Data_01.mdf', fileType: 'ROWS', readStallMs: 4120, writeStallMs: 1820, avgReadLatencyMs: 3.8, avgWriteLatencyMs: 1.4, numReads: 1420500, numWrites: 890400 },
      { dbName: 'ERP_Production', fileName: 'ERP_Log.ldf', fileType: 'LOG', readStallMs: 480, writeStallMs: 3940, avgReadLatencyMs: 1.1, avgWriteLatencyMs: 2.9, numReads: 280400, numWrites: 1350200 },
      { dbName: 'ECommerce_Store', fileName: 'Store_Data.mdf', fileType: 'ROWS', readStallMs: 8920, writeStallMs: 2400, avgReadLatencyMs: 7.2, avgWriteLatencyMs: 2.1, numReads: 1890000, numWrites: 620000 },
      { dbName: 'tempdb', fileName: 'tempdev_01.mdf', fileType: 'ROWS', readStallMs: 210, writeStallMs: 310, avgReadLatencyMs: 0.4, avgWriteLatencyMs: 0.5, numReads: 4200000, numWrites: 3900000 },
      { dbName: 'Analytics_DW', fileName: 'DW_Data_LUN2.ndf', fileType: 'ROWS', readStallMs: 14200, writeStallMs: 4800, avgReadLatencyMs: 12.4, avgWriteLatencyMs: 5.6, numReads: 980000, numWrites: 210000 },
    ],
  },
  sessions: [
    {
      spid: 84,
      status: 'running',
      loginName: 'app_billing_svc',
      hostName: 'K8S-POD-BILLING-7C9F',
      programName: 'Fintech Processing Engine v4.2',
      dbName: 'ERP_Production',
      cpuTimeMs: 48200,
      logicalReads: 4920400,
      writes: 3820,
      durationMs: 94200,
      executionPercent: 68,
      waitType: 'LCK_M_X',
      waitTimeMs: 18450,
      lastWaitType: 'PAGEIOLATCH_SH',
      command: 'UPDATE',
      sqlText: `UPDATE dbo.Invoices
SET Status = 'PROCESSED', ProcessedDate = SYSDATETIME(), BatchID = @BatchGuid
WHERE Status = 'PENDING' AND DueDate <= CAST(GETDATE() AS DATE)
  AND CustomerID IN (SELECT CustomerID FROM dbo.PriorityClients WHERE Tier = 'Enterprise');`,
      blockedBySpid: null,
      openTranCount: 2,
      memoryUsageKB: 32768,
      transactionIsolationLevel: 'ReadCommitted',
      loginTime: '2026-09-01 10:14:22',
      lastRequestStart: '2026-09-01 14:28:10',
    },
    {
      spid: 92,
      status: 'suspended',
      loginName: 'etl_nightly_job',
      hostName: 'SRV-ETL-INTEGRATION',
      programName: 'SQL Server Integration Services (SSIS)',
      dbName: 'ERP_Production',
      cpuTimeMs: 12840,
      logicalReads: 1820400,
      writes: 120,
      durationMs: 45200,
      executionPercent: 42,
      waitType: 'LCK_M_S',
      waitTimeMs: 18450,
      lastWaitType: 'ASYNC_NETWORK_IO',
      command: 'SELECT',
      sqlText: `SELECT i.InvoiceID, i.CustomerID, i.TotalAmount, c.CompanyName
FROM dbo.Invoices i WITH (HOLDLOCK)
INNER JOIN dbo.Customers c ON i.CustomerID = c.CustomerID
WHERE i.Status = 'PENDING';`,
      blockedBySpid: 84,
      openTranCount: 1,
      memoryUsageKB: 16384,
      transactionIsolationLevel: 'RepeatableRead',
      loginTime: '2026-09-01 12:00:00',
      lastRequestStart: '2026-09-01 14:28:40',
    },
    {
      spid: 105,
      status: 'suspended',
      loginName: 'report_portal_user',
      hostName: 'WEB-PORTAL-02',
      programName: '.NET SqlClient Data Provider',
      dbName: 'ERP_Production',
      cpuTimeMs: 8400,
      logicalReads: 920000,
      writes: 0,
      durationMs: 32000,
      executionPercent: 25,
      waitType: 'LCK_M_IS',
      waitTimeMs: 14200,
      lastWaitType: 'LCK_M_IS',
      command: 'SELECT',
      sqlText: `SELECT COUNT(*) AS PendingInvoices, SUM(TotalAmount) AS TotalRevenue
FROM dbo.Invoices
WHERE Status = 'PENDING';`,
      blockedBySpid: 84,
      openTranCount: 0,
      memoryUsageKB: 8192,
      transactionIsolationLevel: 'ReadCommitted',
      loginTime: '2026-09-01 13:45:10',
      lastRequestStart: '2026-09-01 14:29:05',
    },
    {
      spid: 118,
      status: 'running',
      loginName: 'api_storefront',
      hostName: 'AWS-ECS-TASK-STOREFRONT-4',
      programName: 'NodeJS E-Commerce Gateway',
      dbName: 'ECommerce_Store',
      cpuTimeMs: 3100,
      logicalReads: 420100,
      writes: 480,
      durationMs: 8200,
      executionPercent: 88,
      waitType: 'SOS_SCHEDULER_YIELD',
      waitTimeMs: 40,
      lastWaitType: 'CXPACKET',
      command: 'INSERT',
      sqlText: `INSERT INTO dbo.Orders (OrderID, CustomerID, OrderDate, TotalDue, OrderStatus, TrackingNumber)
VALUES (@OrderID, @CustomerID, GETDATE(), @TotalDue, 'Confirmed', @TrackNo);`,
      blockedBySpid: null,
      openTranCount: 1,
      memoryUsageKB: 4096,
      transactionIsolationLevel: 'ReadCommitted',
      loginTime: '2026-09-01 14:10:02',
      lastRequestStart: '2026-09-01 14:29:32',
    },
    {
      spid: 126,
      status: 'running',
      loginName: 'dw_powerbi_refresh',
      hostName: 'PBI-GATEWAY-CLUSTER-01',
      programName: 'Microsoft Power BI Service',
      dbName: 'Analytics_DW',
      cpuTimeMs: 142000,
      logicalReads: 24900000,
      writes: 0,
      durationMs: 240000,
      executionPercent: 74,
      waitType: 'CXCONSUMER',
      waitTimeMs: 320,
      lastWaitType: 'PAGEIOLATCH_SH',
      command: 'SELECT',
      sqlText: `SELECT f.DateKey, p.CategoryName, g.Country,
       SUM(f.SalesAmount) AS TotalSales,
       AVG(f.MarginPct) AS AvgMargin
FROM dbo.FactSales f
INNER JOIN dbo.DimProduct p ON f.ProductKey = p.ProductKey
INNER JOIN dbo.DimGeography g ON f.GeographyKey = g.GeographyKey
WHERE f.DateKey >= 20250101
GROUP BY f.DateKey, p.CategoryName, g.Country
OPTION (MAXDOP 8);`,
      blockedBySpid: null,
      openTranCount: 0,
      memoryUsageKB: 65536,
      transactionIsolationLevel: 'ReadCommittedSnapshot',
      loginTime: '2026-09-01 14:00:00',
      lastRequestStart: '2026-09-01 14:25:40',
    },
    {
      spid: 67,
      status: 'sleeping',
      loginName: 'auth_microservice',
      hostName: 'AUTH-POD-09',
      programName: 'Go-Microservice-Auth/v2',
      dbName: 'Identity_Security',
      cpuTimeMs: 140,
      logicalReads: 1200,
      writes: 10,
      durationMs: 15,
      executionPercent: 100,
      waitType: 'MISCELLANEOUS',
      waitTimeMs: 0,
      lastWaitType: 'ASYNC_NETWORK_IO',
      command: 'AWAITING COMMAND',
      sqlText: `SELECT UserID, PasswordHash, Salt, MFAEnabled FROM dbo.UserCredentials WHERE Username = @Username;`,
      blockedBySpid: null,
      openTranCount: 0,
      memoryUsageKB: 2048,
      transactionIsolationLevel: 'ReadCommitted',
      loginTime: '2026-09-01 08:30:12',
      lastRequestStart: '2026-09-01 14:29:45',
    },
    {
      spid: 71,
      status: 'sleeping',
      loginName: 'audit_daemon',
      hostName: 'SEC-AUDIT-SRV',
      programName: 'SQL Audit Collector',
      dbName: 'Audit_Logs',
      cpuTimeMs: 890,
      logicalReads: 4500,
      writes: 920,
      durationMs: 80,
      executionPercent: 100,
      waitType: 'MISCELLANEOUS',
      waitTimeMs: 0,
      lastWaitType: 'WRITELOG',
      command: 'AWAITING COMMAND',
      sqlText: `INSERT INTO dbo.SecurityEvents (EventType, LoginName, ClientIP, EventTime, Payload) VALUES (@Type, @Login, @IP, GETDATE(), @Data);`,
      blockedBySpid: null,
      openTranCount: 0,
      memoryUsageKB: 2048,
      transactionIsolationLevel: 'ReadCommitted',
      loginTime: '2026-09-01 06:00:00',
      lastRequestStart: '2026-09-01 14:29:10',
    },
  ],
  blocking: {
    totalBlocked: 2,
    longestWaitMs: 18450,
    trees: [
      {
        rootSpid: 84,
        rootLogin: 'app_billing_svc',
        rootHost: 'K8S-POD-BILLING-7C9F',
        rootWaitType: 'PAGEIOLATCH_SH / Transaction Lock',
        rootWaitTimeMs: 18450,
        rootSql: `UPDATE dbo.Invoices SET Status = 'PROCESSED' WHERE Status = 'PENDING' AND DueDate <= GETDATE()...`,
        rootDb: 'ERP_Production',
        blockedCount: 2,
        blockedSessions: [
          {
            spid: 92,
            loginName: 'etl_nightly_job',
            hostName: 'SRV-ETL-INTEGRATION',
            waitType: 'LCK_M_S (Shared Table Lock)',
            waitTimeMs: 18450,
            durationMs: 45200,
            sqlText: `SELECT i.InvoiceID, i.CustomerID FROM dbo.Invoices i WITH (HOLDLOCK)...`,
            blockedBySpid: 84,
          },
          {
            spid: 105,
            loginName: 'report_portal_user',
            hostName: 'WEB-PORTAL-02',
            waitType: 'LCK_M_IS (Intent Shared Lock)',
            waitTimeMs: 14200,
            durationMs: 32000,
            sqlText: `SELECT COUNT(*) AS PendingInvoices FROM dbo.Invoices WHERE Status = 'PENDING'...`,
            blockedBySpid: 84,
          },
        ],
      },
    ],
  },
  deadlocks: [
    {
      id: 'DL-20260901-1402',
      timestamp: '2026-09-01 14:02:18',
      victimSpid: 79,
      victimSql: `UPDATE dbo.AccountBalances SET Balance = Balance - 250.00 WHERE AccountID = 10492;`,
      conflictSpid: 112,
      conflictSql: `UPDATE dbo.AccountBalances SET Balance = Balance + 250.00 WHERE AccountID = 88201;`,
      lockType: 'Key Lock (X/X Conflict)',
      resourceName: 'KEY: 7:72057594047430656 (ERP_Production.dbo.AccountBalances.PK_AccountBalances)',
      xmlReport: `<deadlock>
 <victim-list>
  <victimProcess id="process1402a" />
 </victim-list>
 <process-list>
  <process id="process1402a" taskpriority="0" logused="1240" waitresource="KEY: 7:72057594047430656" waittime="3210" ownerId="892104" transactionname="TransferFund" spid="79" hostname="APP-API-01" loginname="svc_payment">
   <executionStack>
    <frame procname="ERP_Production.dbo.usp_TransferFunds" line="42" sqlhandle="0x030007000..."/>
   </executionStack>
   <inputbuf>EXEC dbo.usp_TransferFunds @FromAcc=10492, @ToAcc=88201, @Amount=250.00</inputbuf>
  </process>
  <process id="process1402b" taskpriority="0" logused="1890" waitresource="KEY: 7:72057594047430656" waittime="3208" ownerId="892109" transactionname="TransferFund" spid="112" hostname="APP-API-02" loginname="svc_payment">
   <executionStack>
    <frame procname="ERP_Production.dbo.usp_TransferFunds" line="42" sqlhandle="0x030007000..."/>
   </executionStack>
   <inputbuf>EXEC dbo.usp_TransferFunds @FromAcc=88201, @ToAcc=10492, @Amount=250.00</inputbuf>
  </process>
 </process-list>
 <resource-list>
  <keylock hobtid="72057594047430656" dbid="7" objectname="ERP_Production.dbo.AccountBalances" indexname="PK_AccountBalances" mode="X">
   <owner-list><owner id="process1402b" mode="X"/></owner-list>
   <waiter-list><waiter id="process1402a" mode="X" requestType="wait"/></waiter-list>
  </keylock>
 </resource-list>
</deadlock>`,
      processes: [
        {
          spid: 79,
          login: 'svc_payment',
          hostname: 'APP-API-01',
          database: 'ERP_Production',
          executionText: 'EXEC dbo.usp_TransferFunds @FromAcc=10492, @ToAcc=88201, @Amount=250.00',
          lockMode: 'Exclusive (X) Lock Wait',
          waitResource: 'KEY: PK_AccountBalances (10492)',
          isVictim: true,
        },
        {
          spid: 112,
          login: 'svc_payment',
          hostname: 'APP-API-02',
          database: 'ERP_Production',
          executionText: 'EXEC dbo.usp_TransferFunds @FromAcc=88201, @ToAcc=10492, @Amount=250.00',
          lockMode: 'Exclusive (X) Lock Owned',
          waitResource: 'KEY: PK_AccountBalances (88201)',
          isVictim: false,
        },
      ],
    },
  ],
  databases: [
    {
      name: 'ERP_Production',
      state: 'ONLINE',
      compatibilityLevel: 160,
      collation: 'SQL_Latin1_General_CP1_CI_AS',
      recoveryModel: 'FULL',
      logReuseWaitDesc: 'LOG_BACKUP',
      totalSizeMB: 2867200,
      dataSizeMB: 2252800,
      logSizeMB: 614400,
      logSpaceUsedPct: 78.4,
      tableCount: 482,
      viewCount: 128,
      spCount: 614,
      growthType: 'Megabytes',
      growthSetting: 'Data: 1024 MB, Log: 512 MB',
      autogrowthRisk: 'Safe',
      lastFullBackup: '2026-09-01 02:00:15',
      lastDiffBackup: '2026-09-01 12:00:08',
      lastLogBackup: '2026-09-01 14:15:00',
      backupHealth: 'healthy',
      growthHistory: [
        { date: 'Aug 01', sizeMB: 2710000 },
        { date: 'Aug 08', sizeMB: 2745000 },
        { date: 'Aug 15', sizeMB: 2782000 },
        { date: 'Aug 22', sizeMB: 2824000 },
        { date: 'Sep 01', sizeMB: 2867200 },
      ],
    },
    {
      name: 'ECommerce_Store',
      state: 'ONLINE',
      compatibilityLevel: 160,
      collation: 'SQL_Latin1_General_CP1_CI_AS',
      recoveryModel: 'FULL',
      logReuseWaitDesc: 'NOTHING',
      totalSizeMB: 1536000,
      dataSizeMB: 1228800,
      logSizeMB: 307200,
      logSpaceUsedPct: 42.1,
      tableCount: 246,
      viewCount: 64,
      spCount: 310,
      growthType: 'Megabytes',
      growthSetting: 'Data: 512 MB, Log: 256 MB',
      autogrowthRisk: 'Safe',
      lastFullBackup: '2026-09-01 03:00:00',
      lastDiffBackup: '2026-09-01 12:30:00',
      lastLogBackup: '2026-09-01 14:20:00',
      backupHealth: 'healthy',
      growthHistory: [
        { date: 'Aug 01', sizeMB: 1420000 },
        { date: 'Aug 08', sizeMB: 1450000 },
        { date: 'Aug 15', sizeMB: 1480000 },
        { date: 'Aug 22', sizeMB: 1510000 },
        { date: 'Sep 01', sizeMB: 1536000 },
      ],
    },
    {
      name: 'Analytics_DW',
      state: 'ONLINE',
      compatibilityLevel: 160,
      collation: 'SQL_Latin1_General_CP1_CI_AS',
      recoveryModel: 'SIMPLE',
      logReuseWaitDesc: 'CHECKPOINT',
      totalSizeMB: 3481600,
      dataSizeMB: 3276800,
      logSizeMB: 204800,
      logSpaceUsedPct: 18.2,
      tableCount: 180,
      viewCount: 240,
      spCount: 195,
      growthType: 'Megabytes',
      growthSetting: 'Data: 2048 MB, Log: 512 MB',
      autogrowthRisk: 'Safe',
      lastFullBackup: '2026-08-31 23:30:00',
      lastDiffBackup: '2026-09-01 11:00:00',
      lastLogBackup: null,
      backupHealth: 'healthy',
      growthHistory: [
        { date: 'Aug 01', sizeMB: 3100000 },
        { date: 'Aug 08', sizeMB: 3200000 },
        { date: 'Aug 15', sizeMB: 3300000 },
        { date: 'Aug 22', sizeMB: 3400000 },
        { date: 'Sep 01', sizeMB: 3481600 },
      ],
    },
    {
      name: 'Identity_Security',
      state: 'ONLINE',
      compatibilityLevel: 150,
      collation: 'SQL_Latin1_General_CP1_CI_AS',
      recoveryModel: 'FULL',
      logReuseWaitDesc: 'LOG_BACKUP',
      totalSizeMB: 102400,
      dataSizeMB: 71680,
      logSizeMB: 30720,
      logSpaceUsedPct: 86.4,
      tableCount: 64,
      viewCount: 18,
      spCount: 92,
      growthType: 'Percent',
      growthSetting: 'Data: 10%, Log: 10%',
      autogrowthRisk: 'Warning',
      lastFullBackup: '2026-09-01 01:15:00',
      lastDiffBackup: '2026-09-01 10:00:00',
      lastLogBackup: '2026-09-01 13:30:00',
      backupHealth: 'warning',
      growthHistory: [
        { date: 'Aug 01', sizeMB: 92000 },
        { date: 'Aug 08', sizeMB: 95000 },
        { date: 'Aug 15', sizeMB: 98000 },
        { date: 'Aug 22', sizeMB: 100000 },
        { date: 'Sep 01', sizeMB: 102400 },
      ],
    },
    {
      name: 'Audit_Logs',
      state: 'ONLINE',
      compatibilityLevel: 150,
      collation: 'SQL_Latin1_General_CP1_CI_AS',
      recoveryModel: 'FULL',
      logReuseWaitDesc: 'ACTIVE_TRANSACTION',
      totalSizeMB: 512000,
      dataSizeMB: 409600,
      logSizeMB: 102400,
      logSpaceUsedPct: 91.2,
      tableCount: 32,
      viewCount: 8,
      spCount: 45,
      growthType: 'Percent',
      growthSetting: 'Data: 10%, Log: 10%',
      autogrowthRisk: 'High',
      lastFullBackup: '2026-08-25 04:00:00',
      lastDiffBackup: null,
      lastLogBackup: '2026-08-26 09:00:00',
      backupHealth: 'critical',
      growthHistory: [
        { date: 'Aug 01', sizeMB: 420000 },
        { date: 'Aug 08', sizeMB: 445000 },
        { date: 'Aug 15', sizeMB: 470000 },
        { date: 'Aug 22', sizeMB: 495000 },
        { date: 'Sep 01', sizeMB: 512000 },
      ],
    },
  ],
  topTables: [
    { schemaName: 'dbo', tableName: 'Invoices', dbName: 'ERP_Production', rowCount: 18450200, totalSpaceMB: 412000, dataSpaceMB: 289000, indexSpaceMB: 118000, unusedSpaceMB: 5000 },
    { schemaName: 'dbo', tableName: 'InvoiceLines', dbName: 'ERP_Production', rowCount: 64200100, totalSpaceMB: 684000, dataSpaceMB: 492000, indexSpaceMB: 188000, unusedSpaceMB: 4000 },
    { schemaName: 'dbo', tableName: 'FactSales', dbName: 'Analytics_DW', rowCount: 142000000, totalSpaceMB: 1420000, dataSpaceMB: 980000, indexSpaceMB: 420000, unusedSpaceMB: 20000 },
    { schemaName: 'dbo', tableName: 'Orders', dbName: 'ECommerce_Store', rowCount: 29400000, totalSpaceMB: 390000, dataSpaceMB: 270000, indexSpaceMB: 115000, unusedSpaceMB: 5000 },
    { schemaName: 'dbo', tableName: 'OrderItems', dbName: 'ECommerce_Store', rowCount: 78500000, totalSpaceMB: 610000, dataSpaceMB: 430000, indexSpaceMB: 172000, unusedSpaceMB: 8000 },
    { schemaName: 'dbo', tableName: 'SecurityEvents', dbName: 'Audit_Logs', rowCount: 38900000, totalSpaceMB: 340000, dataSpaceMB: 240000, indexSpaceMB: 96000, unusedSpaceMB: 4000 },
    { schemaName: 'dbo', tableName: 'CustomerAuditTrail', dbName: 'ERP_Production', rowCount: 12800000, totalSpaceMB: 185000, dataSpaceMB: 130000, indexSpaceMB: 52000, unusedSpaceMB: 3000 },
  ],
  indexUsage: [
    { dbName: 'ERP_Production', tableName: 'Invoices', indexName: 'PK_Invoices_InvoiceID', indexType: 'CLUSTERED', userSeeks: 4820000, userScans: 1240, userLookups: 0, userUpdates: 890400, totalReads: 4821240, readToWriteRatio: 5.41, isUnused: false },
    { dbName: 'ERP_Production', tableName: 'Invoices', indexName: 'IX_Invoices_CustomerID_DueDate', indexType: 'NONCLUSTERED', userSeeks: 3140000, userScans: 410, userLookups: 920000, userUpdates: 890400, totalReads: 4060410, readToWriteRatio: 4.56, isUnused: false },
    { dbName: 'ERP_Production', tableName: 'Invoices', indexName: 'IX_Invoices_LegacyRefCode_OBSOLETE', indexType: 'NONCLUSTERED', userSeeks: 0, userScans: 2, userLookups: 0, userUpdates: 890400, totalReads: 2, readToWriteRatio: 0.00, isUnused: true },
    { dbName: 'ECommerce_Store', tableName: 'Orders', indexName: 'PK_Orders_OrderID', indexType: 'CLUSTERED', userSeeks: 8920000, userScans: 850, userLookups: 0, userUpdates: 620000, totalReads: 8920850, readToWriteRatio: 14.38, isUnused: false },
    { dbName: 'ECommerce_Store', tableName: 'Orders', indexName: 'IX_Orders_TempCouponCode_2023', indexType: 'NONCLUSTERED', userSeeks: 0, userScans: 0, userLookups: 0, userUpdates: 620000, totalReads: 0, readToWriteRatio: 0.00, isUnused: true },
    { dbName: 'Analytics_DW', tableName: 'FactSales', indexName: 'CCI_FactSales', indexType: 'COLUMNSTORE', userSeeks: 0, userScans: 48200, userLookups: 0, userUpdates: 12000, totalReads: 48200, readToWriteRatio: 4.01, isUnused: false },
    { dbName: 'Identity_Security', tableName: 'UserSessions', indexName: 'IX_UserSessions_ClientIP_Old', indexType: 'NONCLUSTERED', userSeeks: 0, userScans: 1, userLookups: 0, userUpdates: 1450000, totalReads: 1, readToWriteRatio: 0.00, isUnused: true },
  ],
  missingIndexes: [
    {
      dbName: 'ERP_Production',
      tableName: 'Invoices',
      impactPct: 87.4,
      userSeeks: 1420500,
      userScans: 38200,
      avgTotalUserCost: 48.2,
      avgUserImpact: 87.4,
      equalityCols: '[Status], [DueDate]',
      inequalityCols: '[CustomerID]',
      includedCols: '[TotalAmount], [BatchID], [ProcessedDate]',
      createScript: `CREATE NONCLUSTERED INDEX [IX_Invoices_Status_DueDate_Inc]
ON [ERP_Production].[dbo].[Invoices] ([Status], [DueDate], [CustomerID])
INCLUDE ([TotalAmount], [BatchID], [ProcessedDate])
WITH (ONLINE = ON, DATA_COMPRESSION = PAGE, FILLFACTOR = 90);`,
    },
    {
      dbName: 'ECommerce_Store',
      tableName: 'Orders',
      impactPct: 74.2,
      userSeeks: 890000,
      userScans: 12400,
      avgTotalUserCost: 22.8,
      avgUserImpact: 74.2,
      equalityCols: '[OrderStatus], [OrderDate]',
      inequalityCols: '',
      includedCols: '[CustomerID], [TotalDue], [TrackingNumber]',
      createScript: `CREATE NONCLUSTERED INDEX [IX_Orders_OrderStatus_OrderDate_Inc]
ON [ECommerce_Store].[dbo].[Orders] ([OrderStatus], [OrderDate])
INCLUDE ([CustomerID], [TotalDue], [TrackingNumber])
WITH (ONLINE = ON, DATA_COMPRESSION = PAGE, FILLFACTOR = 90);`,
    },
    {
      dbName: 'Audit_Logs',
      tableName: 'SecurityEvents',
      impactPct: 92.1,
      userSeeks: 3400000,
      userScans: 89000,
      avgTotalUserCost: 95.4,
      avgUserImpact: 92.1,
      equalityCols: '[EventType]',
      inequalityCols: '[EventTime]',
      includedCols: '[LoginName], [ClientIP]',
      createScript: `CREATE NONCLUSTERED INDEX [IX_SecurityEvents_EventType_EventTime]
ON [Audit_Logs].[dbo].[SecurityEvents] ([EventType], [EventTime])
INCLUDE ([LoginName], [ClientIP])
WITH (ONLINE = ON, DATA_COMPRESSION = PAGE);`,
    },
  ],
  indexFragmentation: [
    {
      dbName: 'ERP_Production',
      schemaName: 'dbo',
      tableName: 'Invoices',
      indexName: 'IX_Invoices_CustomerID_DueDate',
      indexType: 'NONCLUSTERED',
      avgFragmentationPct: 48.7,
      pageCount: 148200,
      sizeMB: 1157,
      actionRecommendation: 'REBUILD',
      actionScript: `ALTER INDEX [IX_Invoices_CustomerID_DueDate] ON [ERP_Production].[dbo].[Invoices] REBUILD WITH (ONLINE = ON, MAXDOP = 4, SORT_IN_TEMPDB = ON);`,
    },
    {
      dbName: 'ERP_Production',
      schemaName: 'dbo',
      tableName: 'InvoiceLines',
      indexName: 'IX_InvoiceLines_InvoiceID',
      indexType: 'NONCLUSTERED',
      avgFragmentationPct: 38.2,
      pageCount: 241000,
      sizeMB: 1882,
      actionRecommendation: 'REBUILD',
      actionScript: `ALTER INDEX [IX_InvoiceLines_InvoiceID] ON [ERP_Production].[dbo].[InvoiceLines] REBUILD WITH (ONLINE = ON, MAXDOP = 4, SORT_IN_TEMPDB = ON);`,
    },
    {
      dbName: 'ECommerce_Store',
      schemaName: 'dbo',
      tableName: 'OrderItems',
      indexName: 'IX_OrderItems_OrderID',
      indexType: 'NONCLUSTERED',
      avgFragmentationPct: 22.4,
      pageCount: 220000,
      sizeMB: 1718,
      actionRecommendation: 'REORGANIZE',
      actionScript: `ALTER INDEX [IX_OrderItems_OrderID] ON [ECommerce_Store].[dbo].[OrderItems] REORGANIZE;`,
    },
    {
      dbName: 'Identity_Security',
      schemaName: 'dbo',
      tableName: 'UserTokens',
      indexName: 'IX_UserTokens_Expiry',
      indexType: 'NONCLUSTERED',
      avgFragmentationPct: 62.1,
      pageCount: 48000,
      sizeMB: 375,
      actionRecommendation: 'REBUILD',
      actionScript: `ALTER INDEX [IX_UserTokens_Expiry] ON [Identity_Security].[dbo].[UserTokens] REBUILD WITH (ONLINE = ON, SORT_IN_TEMPDB = ON);`,
    },
    {
      dbName: 'ERP_Production',
      schemaName: 'dbo',
      tableName: 'Invoices',
      indexName: 'PK_Invoices_InvoiceID',
      indexType: 'CLUSTERED',
      avgFragmentationPct: 4.2,
      pageCount: 369900,
      sizeMB: 2890,
      actionRecommendation: 'HEALTHY',
      actionScript: `-- Index is healthy (< 10% fragmentation). No action needed.`,
    },
  ],
  backupHistory: [
    {
      id: 'BKP-001',
      databaseName: 'ERP_Production',
      type: 'Full',
      backupStartDate: '2026-09-01 02:00:15',
      backupFinishDate: '2026-09-01 02:18:40',
      durationSec: 1105,
      backupSizeMB: 2252800,
      compressedSizeMB: 580000,
      compressionRatio: 3.88,
      serverName: 'PROD-SQL-NODE01',
      userName: 'NT AUTHORITY\\SYSTEM',
      physicalDeviceName: 'B:\\Backups_NFS\\ERP_Production_FULL_20260901_0200.bak',
    },
    {
      id: 'BKP-002',
      databaseName: 'ERP_Production',
      type: 'Differential',
      backupStartDate: '2026-09-01 12:00:08',
      backupFinishDate: '2026-09-01 12:04:12',
      durationSec: 244,
      backupSizeMB: 340000,
      compressedSizeMB: 88000,
      compressionRatio: 3.86,
      serverName: 'PROD-SQL-NODE01',
      userName: 'NT AUTHORITY\\SYSTEM',
      physicalDeviceName: 'B:\\Backups_NFS\\ERP_Production_DIFF_20260901_1200.bak',
    },
    {
      id: 'BKP-003',
      databaseName: 'ERP_Production',
      type: 'Log',
      backupStartDate: '2026-09-01 14:15:00',
      backupFinishDate: '2026-09-01 14:15:22',
      durationSec: 22,
      backupSizeMB: 48000,
      compressedSizeMB: 11200,
      compressionRatio: 4.28,
      serverName: 'PROD-SQL-NODE01',
      userName: 'NT AUTHORITY\\SYSTEM',
      physicalDeviceName: 'B:\\Backups_NFS\\ERP_Production_LOG_20260901_1415.trn',
    },
    {
      id: 'BKP-004',
      databaseName: 'ECommerce_Store',
      type: 'Full',
      backupStartDate: '2026-09-01 03:00:00',
      backupFinishDate: '2026-09-01 03:12:15',
      durationSec: 735,
      backupSizeMB: 1228800,
      compressedSizeMB: 310000,
      compressionRatio: 3.96,
      serverName: 'PROD-SQL-NODE01',
      userName: 'NT AUTHORITY\\SYSTEM',
      physicalDeviceName: 'B:\\Backups_NFS\\Store_FULL_20260901_0300.bak',
    },
    {
      id: 'BKP-005',
      databaseName: 'Audit_Logs',
      type: 'Full',
      backupStartDate: '2026-08-25 04:00:00',
      backupFinishDate: '2026-08-25 04:08:30',
      durationSec: 510,
      backupSizeMB: 409600,
      compressedSizeMB: 98000,
      compressionRatio: 4.17,
      serverName: 'PROD-SQL-NODE01',
      userName: 'NT AUTHORITY\\SYSTEM',
      physicalDeviceName: 'B:\\Backups_NFS\\Audit_Logs_FULL_20260825_0400.bak',
    },
  ],
  alerts: [
    {
      id: 'ALT-01',
      level: 'critical',
      category: 'Backups',
      title: 'Database [Audit_Logs] Missing Full Backup for 7+ Days',
      description: 'The last full backup for database [Audit_Logs] occurred on 2026-08-25 (7 days ago). In FULL recovery mode, this poses significant data loss risk and prevents log truncation.',
      impact: 'RPO breach risk and uncontrolled transaction log growth on Drive L:.',
      recommendation: 'Trigger immediate FULL database backup with compression enabled.',
      fixScript: `BACKUP DATABASE [Audit_Logs]
TO DISK = N'B:\\Backups_NFS\\Audit_Logs_FULL_EMERGENCY.bak'
WITH CHECKSUM, COMPRESSION, STATS = 10, INIT;`,
    },
    {
      id: 'ALT-02',
      level: 'critical',
      category: 'Sessions',
      title: 'Active Blocking Chain Detected (SPID 84 Blocking 2 Sessions)',
      description: 'SPID 84 (app_billing_svc) is holding exclusive locks on dbo.Invoices while running an UPDATE for over 94 seconds, causing SPID 92 and SPID 105 to suspend.',
      impact: 'Application portal and SSIS ETL integration are queued waiting for LCK_M_S locks.',
      recommendation: 'Evaluate killing SPID 84 or tuning the UPDATE query batch size to use indexed chunking.',
      fixScript: `KILL 84; -- Terminate blocker if unresolvable
-- OR execute smaller indexed batch updates:
-- UPDATE TOP (5000) dbo.Invoices ...`,
    },
    {
      id: 'ALT-03',
      level: 'warning',
      category: 'Disk',
      title: 'Drive L:\\ (Transaction Logs) Exceeds 85% Capacity',
      description: 'Volume L:\\ has only 295 GB free out of 2048 GB (85.6% used). [Audit_Logs] and [ERP_Production] have high log file utilization.',
      impact: 'If the log disk reaches 100%, SQL Server will suspend all write transactions server-wide.',
      recommendation: 'Run transaction log backups for FULL databases and check log reuse wait reason.',
      fixScript: `BACKUP LOG [ERP_Production] TO DISK = N'B:\\Backups_NFS\\ERP_Production_Log_Manual.trn' WITH COMPRESSION;
BACKUP LOG [Audit_Logs] TO DISK = N'B:\\Backups_NFS\\Audit_Logs_Log_Manual.trn' WITH COMPRESSION;`,
    },
    {
      id: 'ALT-04',
      level: 'warning',
      category: 'Indexes',
      title: 'Severe Index Fragmentation on [dbo].[Invoices] (48.7%)',
      description: 'Index [IX_Invoices_CustomerID_DueDate] on ERP_Production has 48.7% fragmentation across 148,200 pages, degrading range scan performance.',
      impact: 'Higher logical I/O reads and increased buffer pool memory consumption.',
      recommendation: 'Execute ONLINE Index Rebuild with MAXDOP and SORT_IN_TEMPDB.',
      fixScript: `ALTER INDEX [IX_Invoices_CustomerID_DueDate] ON [ERP_Production].[dbo].[Invoices]
REBUILD WITH (ONLINE = ON, MAXDOP = 4, SORT_IN_TEMPDB = ON);`,
    },
    {
      id: 'ALT-05',
      level: 'info',
      category: 'Indexes',
      title: '3 High-Impact Missing Indexes Identified (Up to 92.1% Gain)',
      description: 'SQL Server Query Optimizer logged missing index requests on [SecurityEvents], [Invoices], and [Orders] with cumulative cost savings of over 85%.',
      impact: 'High query compilation cost and avoidable clustered index table scans.',
      recommendation: 'Review and deploy recommended non-clustered composite indexes.',
    },
  ],
  lastUpdated: new Date().toLocaleTimeString(),
};

/**
 * Generates dynamic ticks for the demo mode simulator so metrics fluctuate realistically
 */
export function simulateNextTelemetryTick(prev: FullMetricsPayload): FullMetricsPayload {
  const timeStr = new Date().toLocaleTimeString();
  
  // Natural CPU jitter
  const deltaCpu = (Math.random() - 0.48) * 8;
  const newSqlCpu = Math.min(96, Math.max(18, Math.round((prev.cpu.sqlProcessUsagePct + deltaCpu) * 10) / 10));
  const newOtherCpu = Math.min(25, Math.max(5, Math.round((prev.cpu.otherProcessesUsagePct + (Math.random() - 0.5) * 3) * 10) / 10));
  const newTotalCpu = Math.min(99, Math.round((newSqlCpu + newOtherCpu) * 10) / 10);
  const newIdle = Math.max(1, Math.round((100 - newTotalCpu) * 10) / 10);

  const updatedHistory = [
    ...prev.cpu.history.slice(1),
    { timestamp: timeStr.slice(0, 5), sqlPct: Math.round(newSqlCpu), totalPct: Math.round(newTotalCpu) },
  ];

  // Dynamic session duration & read ticks
  const updatedSessions = prev.sessions.map((s) => {
    if (s.status === 'running') {
      const addedCpu = Math.floor(Math.random() * 80) + 10;
      const addedReads = Math.floor(Math.random() * 2500) + 100;
      const newDuration = s.durationMs + 2000;
      let newPercent = s.executionPercent + Math.floor(Math.random() * 4) + 1;
      if (newPercent > 99) newPercent = 15;
      return {
        ...s,
        cpuTimeMs: s.cpuTimeMs + addedCpu,
        logicalReads: s.logicalReads + addedReads,
        durationMs: newDuration,
        executionPercent: newPercent,
      };
    }
    if (s.status === 'suspended') {
      return {
        ...s,
        durationMs: s.durationMs + 2000,
        waitTimeMs: s.waitTimeMs + 2000,
      };
    }
    return s;
  });

  return {
    ...prev,
    cpu: {
      ...prev.cpu,
      sqlProcessUsagePct: newSqlCpu,
      otherProcessesUsagePct: newOtherCpu,
      totalUsagePct: newTotalCpu,
      systemIdlePct: newIdle,
      history: updatedHistory,
      workerThreadsCount: prev.cpu.workerThreadsCount + (Math.random() > 0.6 ? (Math.random() > 0.5 ? 2 : -2) : 0),
    },
    memory: {
      ...prev.memory,
      pageLifeExpectancySec: Math.max(300, prev.memory.pageLifeExpectancySec + (Math.random() > 0.5 ? 10 : -8)),
      bufferCacheHitRatioPct: Math.min(99.9, Math.max(98.5, Math.round((prev.memory.bufferCacheHitRatioPct + (Math.random() - 0.5) * 0.1) * 10) / 10)),
    },
    sessions: updatedSessions,
    lastUpdated: timeStr,
  };
}
